# Generated by Django 5.2.17 on 2026-09-16 01:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('book', '图书'), ('series', '系列'), ('level', '级别'), ('set', '套装'), ('animation', '动画'), ('song', '儿歌')], db_index=True, max_length=50)),
                ('display_title', models.CharField(max_length=500)),
                ('title_zh', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('cover_local_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('independent_reading_suitable', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_entities',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogEntityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_entity_categories',
            },
        ),
        migrations.CreateModel(
            name='CatalogEntityReadingPen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_entity_reading_pens',
            },
        ),
        migrations.CreateModel(
            name='CatalogGraphLock',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'catalog_graph_locks',
            },
        ),
        migrations.CreateModel(
            name='CatalogIsbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_type', models.PositiveSmallIntegerField(choices=[(10, 'ISBN-10'), (13, 'ISBN-13')])),
                ('isbn_val', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_isbns',
            },
        ),
        migrations.CreateModel(
            name='CatalogSourceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rating_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_source_stats',
            },
        ),
        migrations.CreateModel(
            name='ChildAbilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=50)),
                ('language_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('syntax_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cognitive_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'db_table': 'child_ability_profiles',
            },
        ),
        migrations.CreateModel(
            name='ChildEntityAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('independent_reading_override', models.BooleanField(blank=True, null=True)),
                ('retry_after_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'child_entity_annotations',
            },
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'child_profiles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collection_items',
                'ordering': [models.OrderBy(models.F('position'), nulls_last=True), 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('age_min_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stage_label', models.CharField(blank=True, max_length=255, null=True)),
                ('material_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reading_lists',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingListCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('background', models.TextField(blank=True, null=True)),
                ('signature_focus', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'reading_list_creators',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stage_label', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_age_min_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended_age_max_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_ar_text', models.CharField(blank=True, max_length=100, null=True)),
                ('source_lexile_text', models.CharField(blank=True, max_length=100, null=True)),
                ('source_level_text', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reading_list_items',
                'ordering': [models.OrderBy(models.F('position'), nulls_last=True), models.OrderBy(models.F('sub_position'), nulls_last=True), 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'reading_pen_models',
            },
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_categories',
                'ordering': ['category_type', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='collection', serialize=False, to='catalog.catalogentity')),
                ('volume_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='work', serialize=False, to='catalog.catalogentity')),
                ('author_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('illustrator_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('language_code', models.CharField(blank=True, max_length=50, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('headword_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ar_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lexile_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.AddConstraint(
            model_name='catalogentity',
            constraint=models.CheckConstraint(condition=models.Q(('entity_type__in', ['animation', 'book', 'level', 'series', 'set', 'song'])), name='catalog_entity_type_valid'),
        ),
        migrations.AddField(
            model_name='catalogentitycategory',
            name='catalog_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.catalogentity'),
        ),
        migrations.AddField(
            model_name='catalogentitycategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='catalog.catalogcategory'),
        ),
        migrations.AddField(
            model_name='catalogentityreadingpen',
            name='catalog_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_pens', to='catalog.catalogentity'),
        ),
        migrations.AddField(
            model_name='catalogsourcestat',
            name='catalog_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_stats', to='catalog.catalogentity'),
        ),
        migrations.AddField(
            model_name='childentityannotation',
            name='catalog_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_annotations', to='catalog.catalogentity'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childentityannotation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_annotations', to='catalog.childprofile'),
        ),
        migrations.AddField(
            model_name='childabilityprofile',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_profiles', to='catalog.childprofile'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='member_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='catalog.catalogentity'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to='catalog.readinglistcreator'),
        ),
        migrations.AddField(
            model_name='readinglistitem',
            name='catalog_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_items', to='catalog.catalogentity'),
        ),
        migrations.AddField(
            model_name='readinglistitem',
            name='reading_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.readinglist'),
        ),
        migrations.AddField(
            model_name='catalogentityreadingpen',
            name='reading_pen_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entities', to='catalog.readingpenmodel'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategory',
            constraint=models.UniqueConstraint(fields=('category_type', 'code'), name='uq_category_code'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.collection'),
        ),
        migrations.CreateModel(
            name='WorkAbilityRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ability_requirement', serialize=False, to='catalog.work')),
                ('language_requirement_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('syntax_requirement_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cognitive_requirement_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('requirement_detail', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'work_ability_requirements',
            },
        ),
        migrations.CreateModel(
            name='WorkDifficultyProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='difficulty_profile', serialize=False, to='catalog.work')),
                ('language_complexity_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('syntax_complexity_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cognitive_load_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('language_detail', models.JSONField(blank=True, null=True)),
                ('syntax_detail', models.JSONField(blank=True, null=True)),
                ('cognitive_detail', models.JSONField(blank=True, null=True)),
                ('analysis_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'work_difficulty_profiles',
            },
        ),
        migrations.AddField(
            model_name='catalogisbn',
            name='work_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbns', to='catalog.work'),
        ),
        migrations.AddConstraint(
            model_name='catalogentitycategory',
            constraint=models.UniqueConstraint(fields=('catalog_entity', 'category'), name='uq_entity_category'),
        ),
        migrations.AddConstraint(
            model_name='catalogsourcestat',
            constraint=models.UniqueConstraint(fields=('source_name', 'external_id'), name='uq_catalog_source_external'),
        ),
        migrations.AddConstraint(
            model_name='childentityannotation',
            constraint=models.UniqueConstraint(fields=('child', 'catalog_entity'), name='uq_child_entity'),
        ),
        migrations.AddConstraint(
            model_name='childabilityprofile',
            constraint=models.UniqueConstraint(fields=('child', 'language_code'), name='uq_child_language'),
        ),
        migrations.AddConstraint(
            model_name='childabilityprofile',
            constraint=models.CheckConstraint(condition=models.Q(('language_score__isnull', True), models.Q(('language_score__gte', 0), ('language_score__lte', 10)), _connector='OR'), name='child_ability_0_range'),
        ),
        migrations.AddConstraint(
            model_name='childabilityprofile',
            constraint=models.CheckConstraint(condition=models.Q(('syntax_score__isnull', True), models.Q(('syntax_score__gte', 0), ('syntax_score__lte', 10)), _connector='OR'), name='child_ability_1_range'),
        ),
        migrations.AddConstraint(
            model_name='childabilityprofile',
            constraint=models.CheckConstraint(condition=models.Q(('cognitive_score__isnull', True), models.Q(('cognitive_score__gte', 0), ('cognitive_score__lte', 10)), _connector='OR'), name='child_ability_2_range'),
        ),
        migrations.AddConstraint(
            model_name='readinglist',
            constraint=models.CheckConstraint(condition=models.Q(('age_min_months__isnull', True), ('age_max_months__isnull', True), ('age_min_months__lte', models.F('age_max_months')), _connector='OR'), name='reading_list_age_order'),
        ),
        migrations.AddConstraint(
            model_name='readinglistitem',
            constraint=models.CheckConstraint(condition=models.Q(('recommended_age_min_months__isnull', True), ('recommended_age_max_months__isnull', True), ('recommended_age_min_months__lte', models.F('recommended_age_max_months')), _connector='OR'), name='reading_item_age_order'),
        ),
        migrations.AddConstraint(
            model_name='catalogentityreadingpen',
            constraint=models.UniqueConstraint(fields=('catalog_entity', 'reading_pen_model'), name='uq_entity_reading_pen'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'member_entity'), name='uq_collection_member'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.CheckConstraint(condition=models.Q(('collection', models.F('member_entity')), _negated=True), name='collection_not_self'),
        ),
        migrations.AddConstraint(
            model_name='workabilityrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('language_requirement_score__isnull', True), models.Q(('language_requirement_score__gte', 0), ('language_requirement_score__lte', 10)), _connector='OR'), name='requirement_0_range'),
        ),
        migrations.AddConstraint(
            model_name='workabilityrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('syntax_requirement_score__isnull', True), models.Q(('syntax_requirement_score__gte', 0), ('syntax_requirement_score__lte', 10)), _connector='OR'), name='requirement_1_range'),
        ),
        migrations.AddConstraint(
            model_name='workabilityrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('cognitive_requirement_score__isnull', True), models.Q(('cognitive_requirement_score__gte', 0), ('cognitive_requirement_score__lte', 10)), _connector='OR'), name='requirement_2_range'),
        ),
        migrations.AddConstraint(
            model_name='workdifficultyprofile',
            constraint=models.CheckConstraint(condition=models.Q(('language_complexity_score__isnull', True), models.Q(('language_complexity_score__gte', 0), ('language_complexity_score__lte', 10)), _connector='OR'), name='difficulty_0_range'),
        ),
        migrations.AddConstraint(
            model_name='workdifficultyprofile',
            constraint=models.CheckConstraint(condition=models.Q(('syntax_complexity_score__isnull', True), models.Q(('syntax_complexity_score__gte', 0), ('syntax_complexity_score__lte', 10)), _connector='OR'), name='difficulty_1_range'),
        ),
        migrations.AddConstraint(
            model_name='workdifficultyprofile',
            constraint=models.CheckConstraint(condition=models.Q(('cognitive_load_score__isnull', True), models.Q(('cognitive_load_score__gte', 0), ('cognitive_load_score__lte', 10)), _connector='OR'), name='difficulty_2_range'),
        ),
        migrations.AddConstraint(
            model_name='catalogisbn',
            constraint=models.UniqueConstraint(fields=('isbn_type', 'isbn_val'), name='uq_catalog_isbn'),
        ),
        migrations.AddConstraint(
            model_name='catalogisbn',
            constraint=models.CheckConstraint(condition=models.Q(('isbn_type__in', [10, 13])), name='chk_catalog_isbn_type'),
        ),
    ]
