# Generated by Django 5.2.17 on 2026-09-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.CharField(max_length=1500)),
                ('source_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_sources',
            },
        ),
        migrations.CreateModel(
            name='ResearchSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('proposed_display_title', models.CharField(blank=True, max_length=500, null=True)),
                ('proposed_title_zh', models.CharField(blank=True, max_length=500, null=True)),
                ('proposed_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('proposed_aliases', models.JSONField(blank=True, null=True)),
                ('research_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('facts_json', models.JSONField(blank=True, null=True)),
                ('ai_inferences_json', models.JSONField(blank=True, null=True)),
                ('research_status', models.CharField(default='pending', max_length=30)),
                ('resolution_status', models.CharField(default='unresolved', max_length=30)),
                ('manual_note', models.TextField(blank=True, null=True)),
                ('research_version', models.CharField(blank=True, max_length=50, null=True)),
                ('researched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_catalog_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogentity')),
            ],
            options={
                'db_table': 'research_subjects',
            },
        ),
        migrations.CreateModel(
            name='ReviewBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=50)),
                ('source_name', models.CharField(blank=True, max_length=500, null=True)),
                ('source_file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_content_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('import_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=30)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('resolved_items', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('target_reading_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.readinglist')),
            ],
            options={
                'db_table': 'review_batches',
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_item_key', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('extracted_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('decision', models.CharField(blank=True, max_length=30, null=True)),
                ('manual_note', models.TextField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reviews.reviewbatch')),
                ('committed_reading_list_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.readinglistitem')),
                ('resolved_catalog_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogentity')),
            ],
            options={
                'db_table': 'review_items',
            },
        ),
        migrations.CreateModel(
            name='ReviewDataConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_path', models.CharField(max_length=255)),
                ('existing_value', models.JSONField(blank=True, null=True)),
                ('proposed_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=30)),
                ('manual_note', models.TextField(blank=True, null=True)),
                ('catalog_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogentity')),
                ('research_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.researchsubject')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.reviewitem')),
            ],
            options={
                'db_table': 'review_data_conflicts',
            },
        ),
        migrations.CreateModel(
            name='ReviewActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('details_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='reviews.reviewitem')),
            ],
            options={
                'db_table': 'review_action_logs',
            },
        ),
        migrations.CreateModel(
            name='ReviewItemSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_role', models.CharField(max_length=30)),
                ('research_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_links', to='reviews.researchsubject')),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='reviews.reviewitem')),
            ],
            options={
                'db_table': 'review_item_subjects',
            },
        ),
        migrations.CreateModel(
            name='ResearchCatalogCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('match_reasons', models.JSONField(blank=True, null=True)),
                ('rank_no', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogentity')),
                ('research_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='reviews.researchsubject')),
            ],
            options={
                'db_table': 'research_catalog_candidates',
                'constraints': [models.UniqueConstraint(fields=('research_subject', 'catalog_entity'), name='uq_subject_candidate')],
            },
        ),
        migrations.CreateModel(
            name='ResearchSubjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='contains', max_length=30)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_type', models.CharField(blank=True, max_length=30, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('review_status', models.CharField(default='proposed', max_length=30)),
                ('member_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='reviews.researchsubject')),
                ('parent_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_relations', to='reviews.researchsubject')),
            ],
            options={
                'db_table': 'research_subject_relations',
                'constraints': [models.UniqueConstraint(fields=('parent_subject', 'member_subject', 'relation_type'), name='uq_research_relation')],
            },
        ),
        migrations.CreateModel(
            name='ResearchSubjectSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='reviews.researchsource')),
                ('research_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='reviews.researchsubject')),
            ],
            options={
                'db_table': 'research_subject_sources',
                'constraints': [models.UniqueConstraint(fields=('research_subject', 'research_source'), name='uq_research_subject_source')],
            },
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['batch', 'status'], name='idx_review_item_batch_status'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(fields=('batch', 'source_item_key'), name='uq_review_item_source_key'),
        ),
        migrations.AddIndex(
            model_name='reviewactionlog',
            index=models.Index(fields=['review_item', 'created_at'], name='idx_review_action_item'),
        ),
        migrations.AddConstraint(
            model_name='reviewitemsubject',
            constraint=models.UniqueConstraint(fields=('review_item', 'research_subject'), name='uq_review_item_subject'),
        ),
    ]
